

update:
	git push origin Alexandros
	git branch -d main
	git branch main
	git push origin main
	git branch -d master
	git branch master
	git push origin master
	git branch -d BackUp
	git branch BackUp
	git push origin BackUp

backup:
	git push origin Alexandros
	git branch -d master
	git branch master
	git push origin master
	git branch -d BackUp
	git branch BackUp
	git push origin BackUp