// <auto-generated />
namespace CBProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Star : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Star));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:CBProject/Migrations/202112011806560_Star.Designer.cs
            get { return "202112011806560_Star"; }
=======
            get { return "202112011142183_Start"; }
>>>>>>> 118d3a5dd2053aa3dd922b06f1b4095713f5a173:CBProject/Migrations/202112011142183_Start.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
