// <auto-generated />
namespace CBProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initiasl1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initiasl1));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:CBProject/Migrations/202112301409197_Initiasl1.Designer.cs
            get { return "202112301409197_Initiasl1"; }
=======
            get { return "202112301140387_Initial"; }
>>>>>>> f0cb8ae527f0ad0118eb2abbb1de942956c65a59:CBProject/Migrations/202112301140387_Initial.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
